apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy11
  labels:
    app: autodeploy11
  namespace: namespace-workflow-1699960751356
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy11
  template:
    metadata:
      labels:
        app: autodeploy11
    spec:
      containers:
        - name: autodeploy11
          image: acrworkflow1699960751356.azurecr.io/image-workflow-1699960751356:latest
          ports:
            - containerPort: 5000